# Generated by Django 5.1 on 2024-11-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codp',
            field=models.IntegerField(null=True),
        ),
    ]
