# Generated by Django 5.1 on 2024-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_alter_user_codp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
